name: NF8-DO-01

on:
  pull_request:
    branches:
      - 'feature/*'
      
jobs:
  verif:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [14,16]
    steps:
      - name: Vérification de la branche
        if: ${{github.event.pull_request.base.ref == 'develop'}}
        uses: actions/checkout@v3
      - name: Setup de Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation des dépendances
        run: npm ci
      - name: Test
        run: npm run test

                

              
            
